language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

matrix:
    allow_failures:
        - php: 7.4snapshot

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - phpenv versions
    - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml

